
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BlackJackTableSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6418, -1, 1, 0}, {6419, 2, 1, 0}, {6426, 0, 1, 0}// 1	2	3	
			, {6426, 1, 1, 0}, {6429, 2, 0, 0}, {6429, -1, 0, 0}// 4	5	6	
			, {2465, 2, 0, 8}// 9	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BlackJackTableSouthAddonDeed();
			}
		}

		[ Constructable ]
		public BlackJackTableSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 7972, 0, 1, 11, 162, -1, "Table", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7973, 1, 1, 11, 162, -1, "table", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3603, -1, 1, 13, 0, -1, "Chips", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3604, -1, 0, 8, 0, -1, "Chips", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4777, 1, 1, 11, 0, -1, "Cards", 1);// 12
			AddComplexComponent( (BaseAddon) this, 4780, 1, 1, 11, 0, -1, "Deck of Cards", 1);// 13

		}

		public BlackJackTableSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BlackJackTableSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BlackJackTableSouthAddon();
			}
		}

		[Constructable]
		public BlackJackTableSouthAddonDeed()
		{
			Name = "BlackJackTableSouth";
		}

		public BlackJackTableSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}