/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_RoundLampAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_RoundLampAddonDeed();
			}
		}

		[ Constructable ]
		public AG_RoundLampAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 9431 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9417 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 6 );

		}

		public AG_RoundLampAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_RoundLampAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_RoundLampAddon();
			}
		}

		[Constructable]
		public AG_RoundLampAddonDeed()
		{
			Name = "AG_RoundLamp";
		}

		public AG_RoundLampAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}