
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SlotMachineEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10082, 1, 0, 1}, {10079, 0, 1, 1}, {10076, 0, 0, 1}// 3	4	5	
			, {10076, 1, 0, 1}// 6	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SlotMachineEastAddonDeed();
			}
		}

		[ Constructable ]
		public SlotMachineEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10761, 1, 1, 1, 0, -1, "Slot Machine", 1);// 1
			AddComplexComponent( (BaseAddon) this, 10082, 1, 1, 0, 0, -1, "Slot Machine", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6855, 1, 1, 21, 0, -1, "Slot Machine", 1);// 7
			AddComplexComponent( (BaseAddon) this, 12221, 1, 0, 4, 0, -1, "Lever", 1);// 8

		}

		public SlotMachineEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SlotMachineEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SlotMachineEastAddon();
			}
		}

		[Constructable]
		public SlotMachineEastAddonDeed()
		{
			Name = "SlotMachineEast";
		}

		public SlotMachineEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}