/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_WayGateWestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_WayGateWestAddonDeed();
			}
		}

		[ Constructable ]
		public AG_WayGateWestAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6958 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6957 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6971 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 479 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3131 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 3523 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3258 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 3248 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6962 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6955 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6953 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6951 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7680 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 466 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 478 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 474 );
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 480 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 3026 );
			AddComponent( ac, 2, 1, 10 );
			ac = new AddonComponent( 14201 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 9036 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 3258 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3250 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 485 );
			AddComponent( ac, 1, 2, 0 );

		}

		public AG_WayGateWestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_WayGateWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_WayGateWestAddon();
			}
		}

		[Constructable]
		public AG_WayGateWestAddonDeed()
		{
			Name = "AG_WayGateWest";
		}

		public AG_WayGateWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}