/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AG_WayGateNorthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AG_WayGateNorthAddonDeed();
			}
		}

		[ Constructable ]
		public AG_WayGateNorthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 476 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 466 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 474 );
			AddComponent( ac, -1, 0, 15 );
			ac = new AddonComponent( 3255 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6958 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6961 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6967 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 14201 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 477 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 481 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 480 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 9036 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6955 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6968 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3025 );
			AddComponent( ac, 1, 1, 10 );

		}

		public AG_WayGateNorthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AG_WayGateNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AG_WayGateNorthAddon();
			}
		}

		[Constructable]
		public AG_WayGateNorthAddonDeed()
		{
			Name = "AG_WayGateNorth";
		}

		public AG_WayGateNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}